// <auto-generated />
namespace KitapEviDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameQuantityPerUnit2toQuantityPerUnitInProductsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameQuantityPerUnit2toQuantityPerUnitInProductsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006141204156_RenameQuantityPerUnit2toQuantityPerUnitInProductsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
